### PR TITLE
Fix comment

### PR DESCRIPTION
**Pull request by mikecaat**

### CODE REVIEW

**Review by rjuju — APPROVED** [review]

**Comment by rjuju** [comment]
Good catch!  Do you want to also update the PR with an updated CONTRIBUTORS.md before I merge it?

**Comment by mikecaat** [comment]
Thanks to check PR!
Although my PR just fixes the comment, if you are ok, please update.

**Comment by rjuju** [comment]
Of course, all contributions are important and welcome!  Please update :)

**Comment by mikecaat** [comment]
Thanks, I updated :)

**Review by rjuju — APPROVED** [review]

**Comment by rjuju** [comment]
Great!  Thanks a lot!

**Pull request merged**
